# Generated by Django 5.2.4 on 2026-01-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_options_remove_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='draft_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
