# Generated by Django 5.2.4 on 2026-01-31 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_webhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_max_debit', models.DecimalField(decimal_places=2, help_text='Maximum amount that can be debited in a month', max_digits=12)),
                ('single_max_debit', models.DecimalField(decimal_places=2, help_text='Maximum amount allowed for a single transaction', max_digits=12)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], default='MONTHLY', help_text='Frequency of the spending limit', max_length=10)),
                ('amount_per_frequency', models.DecimalField(decimal_places=2, help_text='Maximum amount allowed per frequency period', max_digits=12)),
                ('allocations', models.JSONField(blank=True, default=list, help_text="List of fund allocation rules. Example: [{'bucket': 'SAVINGS', 'percentage': 50}, {'bucket': 'SPENDING', 'percentage': 50}]")),
                ('failure_action', models.CharField(choices=[('RETRY', 'Retry Transaction'), ('SKIP', 'Skip Transaction'), ('NOTIFY', 'Notify User')], default='NOTIFY', help_text='Action to take when transaction fails verification', max_length=10)),
                ('start_date', models.DateField(help_text='Date when this rule becomes active')),
                ('end_date', models.DateField(blank=True, help_text='Date when this rule expires (null = indefinite)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rules Engine',
                'verbose_name_plural': 'Rules Engines',
                'ordering': ['-created_at'],
            },
        ),
    ]
