# Generated by Django 5.2.4 on 2026-02-01 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_rulesengine_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current status of the mandate', max_length=10)),
                ('request_ref', models.CharField(help_text='Unique reference for this mandate request', max_length=64, unique=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='Transaction reference from provider (if applicable)', max_length=64)),
                ('activation_url', models.URLField(blank=True, help_text='URL to activate/authorize the mandate (if provider returns one)')),
                ('provider_response', models.JSONField(blank=True, help_text='Raw response from payment provider', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rules_engine', models.ForeignKey(blank=True, help_text='RulesEngine that triggered this mandate creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='api.rulesengine')),
                ('user', models.ForeignKey(help_text='User who owns this mandate', on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mandate',
                'verbose_name_plural': 'Mandates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='api_mandate_user_id_20ffd7_idx'), models.Index(fields=['user', '-created_at'], name='api_mandate_user_id_4a231c_idx')],
            },
        ),
    ]
