"""Add payment_id to Mandate

Revision autogenerated for test workspace.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_mandate"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandate",
            name="payment_id",
            field=models.CharField(max_length=128, blank=True, help_text="Provider payment id used for mandate cancellation"),
        ),
    ]
