"""
Django settings for kore project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url
# corsheaders defaults import used to compose allow lists below
try:
    from corsheaders.defaults import default_headers, default_methods
except ImportError:
    # If django-cors-headers is not installed yet, defaults will be assigned later.
    default_headers = None
    default_methods = None

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-seq(&_(tqk(8m__bxeh%=7&vnre9^b0kq#u98)uc6q^@!x)fa&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#ALLOWED_HOSTS = ['*']  # In development; restrict for production
ALLOWED_HOSTS = [

    "koreapi.onrender.com",
    "*",
]

CSRF_TRUSTED_ORIGINS = [
    "https://koreapi.onrender.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]


MIDDLEWARE = [
    # CORS middleware should be placed as high as possible,
    # especially before any middleware that can generate responses
    # (CommonMiddleware, CsrfViewMiddleware) so that CORS headers
    # are added to responses and preflight requests are handled.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# OnePipe PayWithAccount Configuration
ONEPIPE = {
    "API_KEY": os.getenv("ONEPIPE_API_KEY", ""),
    "CLIENT_SECRET": os.getenv("ONEPIPE_CLIENT_SECRET", ""),
    "WEBHOOK_URL": os.getenv("ONEPIPE_WEBHOOK_URL", ""),
    "BASE_URL": os.getenv("ONEPIPE_BASE_URL", "https://api.dev.onepipe.io"),
    "TRANSACT_PATH": os.getenv("ONEPIPE_TRANSACT_PATH", "/v2/transact"),
}

#ok


# CORS configuration
# By default allow all origins for development. In production,
# set DEBUG=False and provide CORS_ALLOW_ALL_ORIGINS=False and
# CORS_ALLOWED_ORIGINS as comma-separated values.

# Determine CORS policy based on DEBUG setting and environment variable
if DEBUG:
    # Development: allow all origins by default unless explicitly restricted
    CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True").lower() in ("1", "true", "yes")
else:
    # Production: restrict to specific origins by default
    CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False").lower() in ("1", "true", "yes")

CORS_ALLOW_CREDENTIALS = True

# Build allowed headers from corsheaders defaults if available, otherwise use a safe list
if default_headers:
    CORS_ALLOW_HEADERS = list(default_headers) + ["Signature"]
else:
    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
        "signature",
    ]

# Build allowed methods from corsheaders defaults if available
if default_methods:
    CORS_ALLOW_METHODS = list(default_methods)
else:
    CORS_ALLOW_METHODS = [
        "DELETE",
        "GET",
        "OPTIONS",
        "PATCH",
        "POST",
        "PUT",
    ]

# If explicit list of origins provided via env var, use that (production mode)
# Example: export CORS_ALLOWED_ORIGINS="https://example.com,https://admin.example.com"
env_allowed = os.getenv("CORS_ALLOWED_ORIGINS", "").strip()
if env_allowed:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in env_allowed.split(",") if origin.strip()]

